### PR TITLE
fix: multiple field display & switch collection

### PR DESCRIPTION
**Pull request by godkinmo**
For anyone who wants to have quick fix before merge.

```
# composer.json

{
    "require": {
        // ...
        "outl1ne/nova-media-hub": "dev-main",
    },
    "repositories": {
        // ...
        "nova-media-hub": {
            "type": "vcs",
            "url": "https://github.com/godkinmo/nova-media-hub.git"
        }
    }
}
```

Then
```
composer require outl1ne/nova-media-hub:dev-main
```

### CODE REVIEW

**Comment by godkinmo** [comment]
For anyone who wants to have quick fix before merge.

```
# composer.json

{
    "require": {
        // ...
        "outl1ne/nova-media-hub": "dev-main",
    },
    "repositories": {
        // ...
        "nova-media-hub": {
            "type": "vcs",
            "url": "https://github.com/godkinmo/nova-media-hub.git"
        }
    }
}
```

Then
```
composer require outl1ne/nova-media-hub:dev-main
```

**Comment by marcelosantos89** [comment]
I have updated my project but the multiple files still does not show console shows "TypeError: Cannot read properties of undefined (reading 'length')"

**Comment by godkinmo** [comment]
> 

Oh, I see the error too, not test on create resource... I am going to fix this

**Comment by godkinmo** [comment]
@marcelosantos89 just fixed, can try again

**Comment by marcelosantos89** [comment]
It's working now 👍
Thank you

**Comment by marcelosantos89** [comment]
I have noticed something else. 
How to reproduce:
1. Add multiple images to a field and save.
2. Clear all images from that field and save.
3. When you try to add new images it won't save if you click save again it will save empty.

Maybe this bug is not because of your fix if it's not i will add to issues

**Comment by godkinmo** [comment]
Just fixed

**Comment by Tarpsvo** [comment]
Hi @godkinmo! Thanks for your PR. I applied the fixes from your PR to the main branch, but used a different approach to fix the non-casted attribute field not showing any values after saving.

I released your fixes with appropriate credits in version 1.0.1. :) Thanks a ton for helping out!

**Pull request closed without merging**
